
# Site settings
title: "Paul Kalnins, ND, MS"
subtitle: ""
email: "drpkalnins@gmail.com"
description: >-
  Healthcare analytics, clinical data, and systems-oriented perspectives on physiology, resilience, and chronic disease.
baseurl: ""
#baseurl: "/main-website"
url: "https://pkalnins.github.io"
minimal_mistakes_skin: "default"


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Author info (optional)
author:
  name: "Paul Kalnins"
  avatar: "/assets/images/paul.jpg" # place your photo in /assets/images/
  bio: "bio: "Healthcare analytics and clinical data professional with a background in physiology and clinical medicine. Focused on real-world data, longitudinal analysis, and interpretable models of health and disease."
  location: "Portland, OR"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:drpkalnins@gmail.com"
      type: "external"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/pkalnins9"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/pkalnins"
    - label: "Substack"
      icon: "fab fa-pen-nib"
      url: "https://pkalnins.substack.com"
      


# Navigation
navigation: 
  main: main


# Footer (optional)
footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:drpkalnins@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/pkalnins9"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/pkalnins"
    - label: "Substack"
      icon: "fas fa-pen-nib"  # use any Font Awesome icon you like
      url: "https://pkalnins.substack.com"
      type: "external"

# Theme settings
theme: minimal-mistakes-jekyll

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/

# Make sure Jekyll processes the _pages folder
include:
  - _pages


